services:
  # Y-ride ROS2 workspace
  FactorGraphSLAM:
    build:
      context: ${HOME}/FactorGraphSLAM633 # TODO: Set context
      dockerfile: Dockerfile
      args: # These arguments help set the owner of the container files to the host user
        UID: "${UID:-$(id -u)}"
        GID: "${GID:-$(id -g)}"
        UNAME: "docker" # User name of container user
    image: factor_graph_slam_img
    container_name: factor_graph_slam
    user: "${UID}:${GID}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Needed to display RViz within the container
      - ${HOME}/FactorGraphSLAM633/ros_ws:/docker_SLAM/ros2_ws:rw
    environment:
      DISPLAY: ${DISPLAY} # Needed to display RViz within the container
      # set up sensor hostname IPv4 addresses
      SENSOR_HOSTNAME_TOP: ${SENSOR_HOSTNAME_TOP}
      SENSOR_HOSTNAME_FRONT: ${SENSOR_HOSTNAME_FRONT}
      SENSOR_HOSTNAME_RIGHT: ${SENSOR_HOSTNAME_RIGHT}
      SENSOR_HOSTNAME_LEFT: ${SENSOR_HOSTNAME_LEFT}
      SENSOR_HOSTNAME_BACK: ${SENSOR_HOSTNAME_BACK}
      ROS_DOMAIN_ID: 1 # ROS2 domain ID needs to be the same for all containers that comunicate with each other
    # working_dir: /docker_yride/yride_ros2_ws
    stdin_open: true
    tty: true
    network_mode: host