services:
  # Y-ride ROS2 workspace
  FactorGraphSLAM:
    build:
      context: ${HOME}/tello_ros2
      dockerfile: Dockerfile
    image: tello_ros2_image
    container_name: tello
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Needed to display RViz within the container
      - ${HOME}/tello_ros2/ros2_ws:/tello_ros2/ros2_ws:rw
    environment:
      DISPLAY: ${DISPLAY} # Needed to display RViz within the container
      ROS_DOMAIN_ID: 1 # ROS2 domain ID needs to be the same for all containers that comunicate with each other
    stdin_open: true
    tty: true
    network_mode: host